config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :games

  resources :locations

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :manufacturer, presence: true
  validates :release_date,
              numericality: {
                  only_integer: true,
                  greater_than_or_equal_to: 1970,
                  less_than_or_equal_to: 1989,
                  message: 'The release date must be between 1970 and 1989.'
              }
  belongs_to :manufacturer
  has_many :arcades, inverse_of: :game
  has_many :locations, through: :arcades
  accepts_nested_attributes_for :arcades
  has_many :comments, as: :commentable

  scope :released_in, ->(year) { where('release_date = ?', year) }

  scope :popular, -> {
    joins(:arcades).select('games.*, location_id, count(game_id) as `game_count`')
    .group(:game_id)
    .order('game_count desc')
  }

  extend FriendlyId
  friendly_id :name, :use => :slugged
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.order('name asc').paginate(:page => params[:page],
      :per_page => 20)
  end

  def show
    @game = Game.friendly.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

  <h1>Games</h1>

<% if @games.size > 0 %>

    <ul class="list-group">

      <% @games.each do |game| %>
          <li class="list-group-item">
            <h4 class="list-group-item-heading"><%= link_to game.name, game_path(game.friendly_id) %></h4>
            <span style="color:grey"><%= game.description %></span>
          </li>
      <% end %>

    </ul>

    <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>

<% else %>

    <p>No games available.</p>

<% end %>

</div>
</div>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

    <h1><%= @game.name %></h1>

    <p>
      <%= @game.name %> was released in <%= @game.release_date %> by <%= @game.manufacturer.name %>.
    </p>

    <p>
      ArcadeNomad is tracking <%= @game.name %> in <%= pluralize(@game.locations.count, 'arcade') %>. If you know of
      an arcade hosting <%= @game.name %>, <%= link_to 'let us know', new_location_path %>!
    </p>

  </div>
</div>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>