config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :games

  resources :locations

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :locations, dependent: :restrict_with_error

  validates_presence_of :name

  extend FriendlyId
  friendly_id :name, :use => :slugged
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate

  layout 'admin'

  def index
    @categories = Category.order('name asc')
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category successfully updated.'
      redirect_to edit_admin_category_path(@category.id)
    else
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.where('locations_count > 0').order('name asc')
  end

  def show
    @category = Category.friendly.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form_category.html.erb
<%= form_for [:admin, @category], :url => admin_category_path(@category.id), :html => {'role' => 'form'} do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => 'Must be unique. e.g. Bowling Alley', :class => 'form-control' %>
    </div>

    <div class="form-group">
      <button type="submit" class="btn">Submit</button>
    </div>

<% end %>

app/views/admin/categories/create.html.erb
<h1>Admin::Categories#create</h1>
<p>Find me in app/views/admin/categories/create.html.erb</p>

app/views/admin/categories/edit.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-12">

    <h1>Edit a Category</h1>

    <% if @category.errors.any? %>
        <div>
          <h2><%= pluralize(@category.errors.count, 'error') %> prohibited this category from being updated:</h2>
          <ul>
            <% @category.errors.messages.values.each do |message| %>
                <li><%= message[0] %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render :partial => 'form_category', :locals => { :form => @category } %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-12">
    <h1>Categories</h1>
    <p>
      Tracking <%= Category.count %> categories.
    </p>
    <% if @categories.length > 0 %>
        <table class="table table-striped">
          <% @categories.each do |category| %>
              <tr>
                <td>
                  <h4 class="list-group-item-heading"><%= link_to category.name, edit_admin_category_path(category.id) %></h4>
                </td>
              </tr>
          <% end %>
        </table>
    <% else %>
        <p>No categories available.</p>
    <% end %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<%= link_to category.name, edit_admin_category_path(category) %>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>

app/views/admin/categories/update.html.erb
<h1>Admin::Categories#update</h1>
<p>Find me in app/views/admin/categories/update.html.erb</p>